# Generated by Django 5.1.5 on 2025-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data', models.CharField(max_length=128)),
                ('iata', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
