# Generated by Django 5.1.5 on 2025-02-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(default=True, max_length=128),
        ),
    ]
