# Generated by Django 5.1.5 on 2025-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_delete_city_airport_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=128),
        ),
    ]
