# Generated by Django 5.1.5 on 2025-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_airport_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='name',
            new_name='airport',
        ),
        migrations.AddField(
            model_name='airport',
            name='time',
            field=models.TimeField(blank=True, default='12:30:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
