# Generated by Django 5.1.5 on 2025-02-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_rename_name_airport_airport_airport_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='airport',
            name='time',
            field=models.TimeField(),
        ),
    ]
