# Generated by Django 5.1.5 on 2025-02-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_alter_airport_data_alter_airport_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='data',
            new_name='date',
        ),
    ]
