# Generated by Django 5.1.5 on 2025-02-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_rename_data_airport_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'managed': False},
        ),
    ]
