# Generated by Django 5.1.5 on 2025-02-10 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0005_rename_from_iata_flight_fromi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('document_number', models.CharField(max_length=128)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_flight', to='flights.flight')),
            ],
        ),
    ]
