# Generated by Django 5.1.5 on 2025-02-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(max_length=75)),
            ],
        ),
    ]
