# Generated by Django 5.1.5 on 2025-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_document_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='booking.passenger'),
        ),
    ]
