# Generated by Django 5.1.5 on 2025-02-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_passenger_booking_booking_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passengers',
        ),
        migrations.AddField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_booking', to='booking.booking'),
        ),
    ]
