# Generated by Django 5.1.5 on 2025-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='data_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
