# Generated by Django 5.1.5 on 2025-01-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('iata', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=10)),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('cost', models.DecimalField(decimal_places=1, max_digits=10)),
                ('passengers', models.IntegerField()),
                ('from_iata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport')),
                ('to_iata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivalsr', to='flights.airport')),
            ],
        ),
    ]
