# Generated by Django 5.1.5 on 2025-02-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_city'),
        ('flights', '0002_rename_passengers_flight_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='to_iata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivale', to='airport.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='from_iata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='airport.airport'),
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
