# Generated by Django 5.1.5 on 2025-02-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_airport_city'),
        ('flights', '0003_alter_flight_to_iata_alter_flight_from_iata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='to_iata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='airport.airport'),
        ),
    ]
