# Generated by Django 5.1.5 on 2025-02-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_rename_from_iata_flight_fromi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='date1',
            new_name='date_1',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='date2',
            new_name='date_2',
        ),
    ]
