# Generated by Django 5.1.5 on 2025-02-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_rename_date1_flight_date_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='date_1',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='date_2',
        ),
    ]
