# Generated by Django 5.1.5 on 2025-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_remove_flight_date_1_remove_flight_date_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date_1',
            field=models.DateField(default='2020-10-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='date_2',
            field=models.DateField(default='2020-10-13'),
            preserve_default=False,
        ),
    ]
