# Generated by Django 5.1.5 on 2025-02-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_flight_date_1_flight_date_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='date_1',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='date_2',
        ),
    ]
