# Generated by Django 5.1.5 on 2025-02-13 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_rename_data_airport_date'),
        ('flights', '0009_remove_flight_date_1_remove_flight_date_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_date',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='flight_date', to='airport.airport'),
            preserve_default=False,
        ),
    ]
